config/routes.rb
Rails.application.routes.draw do  
  get "welcome/index"  
  root to: "welcome#index"
  resources :articles  
end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    @article.save
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
    @article.save
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = "Article was updated successfully."
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<div class="bg-image" style=" background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.webp');height: 100vh; background-attachment: fixed;">
<div class="h1 text-center pt-3 pb-3">Create Article</div>

<div class="container">
	<div class="jumbotron bg-dark p-4 mb-5">
			<%= form_with(model: @article, local: true) do |f| %>
				<%# Titulo %>
					<label for="exampleInputEmail1" class="form-label text-light"><%= f.label :title %></label>
					<%= f.text_field :title, class:"form-control" %>
					<div id="emailHelp" class="form-text mb-3">Escribe un titulo para tu articulo.</div>
				<%# Description %>
					<label for="exampleInputEmail1" class="form-label text-light"><%= f.label :description %></label>
					<%= f.text_area :description, class:"form-control textoarea" %>
					<div id="emailHelp" class="form-text mb-3">Escribe una descripcion para tu articulo.</div>
				<%# Botones %>
				<div class="d-flex justify-content-center container">
					<div class="row gap-5">	
                        <%= link_to "Cancelar", articles_path, class:"btn btn-primary btn-md col" %>
						<%= f.submit class:"btn btn-primary btn-md col" %>
					</div>
				</div>
			<% end %>	
	</div>
</div>

app/views/articles/index.html.erb
<div class="bg-image" style=" background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.webp');height: 100%;background-attachment: fixed;">

<div class="h1 text-center pt-3 pb-3">ARTICLES</div>

<code></code>

<div class="justify-content-center d-flex container">
<%= link_to "Create Article", new_article_path, class: "btn btn-success col mb-4" %>
</div>

<div class="container pb-5">
	<% @articles.each do |article| %>
		<div class="jumbotron bg-dark p-4 mb-5">

      <%# Titulo %>
			<h1 class="display-4 text-light text-center"><%= link_to article.title, article_path(article), class: "display-4 text-light text-center" %></h1>
			

			<%# Description %>

			<%# Botones %>
			<div class="d-flex justify-content-center container">
				<div class="row gap-5">	
					<%= link_to "Mostrar", article_path(article), class: "btn btn-primary btn-md col" %>
					<%= link_to "Borrar", article_path(article),method: :delete, class: "btn btn-danger btn-md col", data: {confirm: "Are you sure?"} %>
				</div>	
			</div>

			<%# Información de tiempo %>
		  <div id="emailHelp" class="form-text mt-4 text-center">
				<small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago</small>
			</div>

		</div>
	<% end %>
</div>

app/views/articles/new.html.erb
<div class="bg-image" style=" background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.webp');height: 100vh; background-attachment: fixed;">
<div class="h1 text-center pt-3 pb-3">Create Article</div>

<div class="container">
	<div class="jumbotron bg-dark p-4 mb-5">
			<%= form_with scope: :article, url: articles_path, local: true do |f| %>
				<%# Titulo %>
					<label for="exampleInputEmail1" class="form-label text-light"><%= f.label :title %></label>
					<%= f.text_field :title, class:"form-control" %>
					<div id="emailHelp" class="form-text mb-3">Escribe un titulo para tu articulo.</div>
				<%# Description %>
					<label for="exampleInputEmail1" class="form-label text-light"><%= f.label :description %></label>
					<%= f.text_area :description, class:"form-control" %>
					<div id="emailHelp" class="form-text mb-3">Escribe una descripcion para tu articulo.</div>
				<%# Botones %>
				<div class="d-flex justify-content-center container">
					<div class="row gap-5">
						<%= link_to "Back", articles_path, class: "btn btn-primary btn-md col" %>	
						<%= f.submit class:"btn btn-primary btn-md col" %>
					</div>
				</div>
			<% end %>	
	</div>
</div>


	    

app/views/articles/show.html.erb
<div class="bg-image" style=" background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.webp');height: 100%;">

		<div class="jumbotron p-4 mb-5">

      <%# Titulo %>
			<h1 class="display-4 text-dark text-center"><%= @article.title %></h1>
			
			<%# Description %>
			<p class="lead text-dark text-center"><%= @article.description %></p>
			<hr class="my-4 text-light">
			<p class="lead">

			<%# Botones %>
			<div class="d-flex justify-content-center container">
				<div class="row gap-5">	
				</div>	
			</div>

			<%# Información de tiempo %>
		  <div id="emailHelp" class="form-text mt-4 text-center">
				
			</div>
      <div class="container">
<%= link_to "Editar", edit_article_path(@article), class: "btn btn-warning btn-md w-100 col mb-3" %>
<%= link_to "Regresar", articles_path(@article), class: "btn btn-primary btn-md w-100 col mb-3" %>
</div>
		</div>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Warning !! ensure that "stylesheet_pack_tag" is used, line below -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
<!-- inside app/views/welcome/index.html.erb -->  
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
     <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand text-light", id: "logo" %>
    <button class="navbar-toggler navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse bg-dark " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active text-light", id: "logo" %>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

  
  <footer class="bg-dark text-center text-lg-start fixed-bottom">
  <!-- Copyright -->
  <div class="text-center text-light p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-light" href="https://google.com/">BlogPryyyy.com</a>
  </div>
  <!-- Copyright -->
</footer>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<main>
  <div class="bg-image" style=" background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.webp');height: 100vh;">
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto" >
          <h1 class="fw-light">ALPHA BLOG</h1>
          <p class="lead text-muted">Bienvenido a mi pequeño proyecto, en donde podrás postear tu propio blog de manera gratuita, espero que te guste y puedas publicar algún blog interesante.</p>
          <p>
            <%= link_to "Encontrar Blog", articles_path, class: "btn btn-primary my-2" %>
            <%= link_to "Publicar Blog", new_article_path, class: "btn btn-secondary my-2" %>
          </p>
        </div>
      </div>
    </section>
  </div>
</main>